### ISSUE TITLE
Water Tracker

### ISSUE THREAD

**Issue by KKetter** [KKetter/201Project#17]
Add Field to Form
Add seperate Table
Add Event Listener
Local Storage

**Comment by KKetter** [comment]
modifying table graphic display to a fix Y axis IOT nest with CSS effects to create droplet look

**Comment by ntibbals** [comment]
Completed field to form, data inputs now populating into water tracker, limited total amount allowed in chart in order to fit water drop, designed initial alert message when hit maximum water recommended, persistent application through the use of local storage
